force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Sighting__c/Animal_Sighting__c.object-meta.xml
<CustomObject>
    <label>Animal Sighting</label>
    <nameField>
        <displayFormat>Sighting-{000000000}</displayFormat>
        <label>Animal Sighting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Sightings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Sighting__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Sightings</relationshipLabel>
    <relationshipName>Animal_Sightings1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Sighting__c/fields/Park__c.field-meta.xml
<CustomField>
    <fullName>Park__c</fullName>
    <label>Park</label>
    <referenceTo>Park__c</referenceTo>
    <relationshipLabel>Animal Sightings</relationshipLabel>
    <relationshipName>Animal_Sightings1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Park__c/Park__c.object-meta.xml
<CustomObject>
    <label>Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ParkAnimalSightingController.cls
public with sharing class ParkAnimalSightingController {

  //translates Park ID into list of Sighted Known Animals
  @AuraEnabled
  static public List<Animal__c> findAnimalImages(id parkId) {
    List<Animal_Sighting__c> sas = [SELECT ID, Animal__c, Animal__r.Name, Animal__r.Image_Link__c from Animal_Sighting__c where Park__c =: parkID];
    List<Animal__c> kas = new List<Animal__c>();
    for(Animal_Sighting__c a : sas) {
      kas.add(new Animal__c(name = a.Animal__r.Name, Image_Link__c = a.Animal__r.Image_Link__c));
    }
        
      return kas;
    }
}